steps:
  - name: "gcr.io/kaniko-project/executor:latest"
    args:
      [
        "--dockerfile=./typescript/packages/api/Dockerfile",
        "--context=./typescript",
        "--destination=${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/api:$SHORT_SHA",
        "--cache=true",
        "--cache-ttl=6h",
      ]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "${_PROJECT_SLUG}-api",
        "--image",
        "${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/api:$SHORT_SHA",
        "--region",
        "${_LOCATION}",
        "--platform",
        "managed",
      ]
options:
  logging: CLOUD_LOGGING_ONLY
