steps:
  - name: "gcr.io/kaniko-project/executor:latest"
    args:
      [
        "--dockerfile=./python/springtime/Dockerfile",
        "--context=./python",
        "--destination=${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/ml-svc:$SHORT_SHA",
        "--cache=true",
        "--cache-ttl=6h",
      ]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "${_PROJECT_SLUG}-ml-svc",
        "--image",
        "${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/ml-svc:$SHORT_SHA",
        "--region",
        "${_LOCATION}",
        "--platform",
        "managed",
      ]
options:
  logging: CLOUD_LOGGING_ONLY
