steps:
  - name: "gcr.io/kaniko-project/executor:latest"
    args:
      [
        "--dockerfile=./typescript/packages/job-runner/Dockerfile",
        "--context=./typescript",
        "--destination=${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/job-runner:$SHORT_SHA",
        "--cache=true",
        "--cache-ttl=6h",
      ]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "artifacts",
        "docker",
        "tags",
        "add",
        "${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/job-runner:$SHORT_SHA",
        "${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/job-runner:latest",
      ]
  - name: "bash"
    script: |
      #!/usr/bin/env bash
      echo "Hello world!"
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    env:
      - "PROJECT_ID=$PROJECT_ID"
      - "_LOCATION=$_LOCATION"
      - "_REPOSITORY=$_REPOSITORY"
      - "SHORT_SHA=$SHORT_SHA"
    args:
      - "-eEuo"
      - "pipefail"
      - "-c"
      - |-
        #!/usr/bin/env bash
        for app in $(gcloud run jobs list  | grep job-runner | awk '{print $2}'); do
          echo $app
          echo "${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/job-runner:${SHORT_SHA}"
          echo "${_LOCATION}"
          gcloud beta run jobs update $app --image "${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/job-runner:${SHORT_SHA}" --region "${_LOCATION}"
        done

options:
  logging: CLOUD_LOGGING_ONLY
