steps:
  - name: "gcr.io/kaniko-project/executor:latest"
    args:
      [
        "--dockerfile=./python/springtime/Dockerfile",
        "--context=./python/springtime",
        "--destination=${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/springtime:$SHORT_SHA",
        "--cache=true",
        "--cache-ttl=6h",
      ]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "artifacts",
        "docker",
        "tags",
        "add",
        "${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/springtime:$SHORT_SHA",
        "${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/springtime:latest",
      ]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "${_PROJECT_SLUG}-springtime",
        "--image",
        "${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/springtime:$SHORT_SHA",
        "--region",
        "${_LOCATION}",
        "--platform",
        "managed",
      ]
options:
  logging: CLOUD_LOGGING_ONLY
